// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContent))]
    [Migration("20251006194232_AdicionaNovasEntidades")]
    partial class AdicionaNovasEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("API.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlunoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMatricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("API.Models.Exercicio", b =>
                {
                    b.Property<int>("ExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExercicioDescricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExercicioNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ExercicioId");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("API.Models.PlanoDeTreino", b =>
                {
                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtribuicao")
                        .HasColumnType("TEXT");

                    b.Property<int>("TreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TreinoId");

                    b.ToTable("PlanosDeTreino");
                });

            modelBuilder.Entity("API.Models.Treino", b =>
                {
                    b.Property<int>("TreinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoTreino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FocoMuscular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TreinoId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("API.Models.PlanoDeTreino", b =>
                {
                    b.HasOne("API.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Treino");
                });
#pragma warning restore 612, 618
        }
    }
}
