// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContent))]
    [Migration("20251019014625_AdicionaRegistroTreinoEDetalhes")]
    partial class AdicionaRegistroTreinoEDetalhes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("API.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataNascimento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMatricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("API.Models.DetalheRegistro", b =>
                {
                    b.Property<int>("DetalheRegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Carga")
                        .HasColumnType("REAL");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistroTreinoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalheRegistroId");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("RegistroTreinoId");

                    b.ToTable("DetalhesRegistro");
                });

            modelBuilder.Entity("API.Models.Exercicio", b =>
                {
                    b.Property<int>("ExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExercicioDescricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExercicioNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExercicioId");

                    b.HasIndex("TreinoId");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("API.Models.PlanoDeTreino", b =>
                {
                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtribuicao")
                        .HasColumnType("TEXT");

                    b.Property<int>("TreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TreinoId");

                    b.ToTable("PlanosDeTreino");
                });

            modelBuilder.Entity("API.Models.RegistroTreino", b =>
                {
                    b.Property<int>("RegistroTreinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistroTreinoId");

                    b.HasIndex("TreinoId");

                    b.ToTable("RegistrosTreino");
                });

            modelBuilder.Entity("API.Models.Treino", b =>
                {
                    b.Property<int>("TreinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoTreino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FocoMuscular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TreinoId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("API.Models.DetalheRegistro", b =>
                {
                    b.HasOne("API.Models.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.RegistroTreino", "RegistroTreino")
                        .WithMany("Detalhes")
                        .HasForeignKey("RegistroTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("RegistroTreino");
                });

            modelBuilder.Entity("API.Models.Exercicio", b =>
                {
                    b.HasOne("API.Models.Treino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("TreinoId");
                });

            modelBuilder.Entity("API.Models.PlanoDeTreino", b =>
                {
                    b.HasOne("API.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("API.Models.RegistroTreino", b =>
                {
                    b.HasOne("API.Models.Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("TreinoId");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("API.Models.RegistroTreino", b =>
                {
                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("API.Models.Treino", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
